highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://estatup.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Eduardo Vargas Ferreira
name: Eduardo Vargas Ferreira
email: e.ferreira@ufpr.br
email_full: mailto:e.ferreira@ufpr.br
website: github.io/sustain
website_full: https://estatup.github.io/sustain
tel:  +55 41 3361 3141 
tel_full: tel: +55 41 3361 3141 
google_maps: 'https://www.google.com/maps/place/Setor+de+Exatas+UFPR/@-25.4501079,-49.2330803,17z/data=!3m1!4b1!4m5!3m4!1s0x94dce50fe3500deb:0xa70fde7b77c59935!8m2!3d-25.4501128!4d-49.2308863'
address:
  street: Rua Cel. Francisco Heráclito dos Santos, 100
  postcode: 81531-980 
  city: Curitiba - PR

# needed for travis-ci build
exclude: [vendor]
 
